Initial Setup of Storybook, React App, CICD deploy to GitHub pages
rucio/webui pull request #16
Opened 2022-06-06 14:38 UTC by nimishbongale

Initial Setup of:

1) Storybook (runs on port 6006)
2) React App (runs on port 3000)
3) CI CD configured for pushes to master, auto deploys to GitHub pages

Sample deployment (may require repo setting changes)

https://nimishbongale.github.io/webui/

2022-06-08 02:26 UTC, maany commented on .github/workflows/build-deploy-storybook.yml
> +            - name: Deploy 🚀
replace with a custom script to push to gh-pages branch  :)

2022-06-08 02:27 UTC, maany commented on LICENSE
> -                                 Apache License
We'd have to keep this file :)

2022-06-08 02:28 UTC, maany commented on package.json
> -    "description": "The official webui for Rucio",
keep the description and keywords as well

2022-06-08 02:30 UTC, maany requested changes
Good work @nimishbongale!! :D Just minor changes besides the CI workflow where you'd have to provide a custom script to push to gh-pages branch ;)

2022-06-09 08:38 UTC, nimishbongale commented
> CI workflow where you'd have to provide a custom script to push to gh-pages branch

@maany Can I take this up as a part of a separate item?

2022-06-10 12:43 UTC, maany approved these changes
LGTM! Kudos, first PR

2022-06-10 12:44 UTC, merged