Fix redirect authenticated users to dashboard
rucio/webui pull request #406
Opened 2024-04-04 20:20 UTC by esilvaju

Fixes #405

2024-04-05 13:44 UTC, maany requested changes

2024-04-05 13:44 UTC, maany commented on src/app/page.tsx
> +import { redirect, RedirectType } from 'next/navigation';
RedirectType is an unused import

2024-04-05 13:53 UTC, esilvaju commented on src/app/page.tsx
> +import { redirect, RedirectType } from 'next/navigation';
Done !

2024-04-19 09:13 UTC, maany approved these changes

2024-04-19 09:13 UTC, merged